### PR TITLE
[Dinesh] Provision to give custom ssh path

### PR DESCRIPTION
**Pull request by dineshba**
Signed-off-by: Dinesh <dineshudt17@gmail.com>

Provision to give custom ssh path using env variable `GG_SSH_PATH`

### CODE REVIEW

**Comment by jpninanjohn** [comment]
Does it read only from env ??

**Comment by dineshba** [comment]
Currently Yes. Should this be part of `.ggConf` file also ?

**Comment by jpninanjohn** [comment]
yeah i was working on tat only

**Comment by jpninanjohn** [comment]
@dineshba I finished the custom ssh via config file. But I dont think custom ssh path via env is needed anymore. Its refactored to work from a single place in the code(`conf.rs`). Also it allows the ssh config to be handled by the ssh agent directly. I have removed this implementation from `fetch.rs` for now. If you think a env is still needed, I will add it to the `conf.rs`. 

Thoughts?

**Comment by dineshba** [comment]
If the git remote is ssh based (not http based), git will talk to remote using ssh. ssh key to be used, by the ssh-agent can be configured at `~/.ssh/config`
Example:
```sh
Host gitlab.xxx.it
    HostName gitlab.xxx.it
    User git
    IdentityFile ~/.ssh/id_ed25519

#Personal Account
Host github.com
    HostName github.com
    User git
    IdentityFile ~/.ssh/id_rsa
```

For gitlab it is one key and github one key. Best solution is to read this file and use automatically. I created env based as a quick/hacky fix. Thoughts ?

I couldn't able to find a library to read this file. May be you can also try to find one. If not, we can write custom code to parse this file and choose the correct ssh private key based on the git remote.

**Comment by jpninanjohn** [comment]
Can you try this scenario by setting up `ssh_agent: true` in gg conifg. For me this worked out of the box. People can give which ssh file to use in the config file separately if they want. But if they choose theay can just let the ssh-agent take care of it. It automatically uses the correct ssh key to access. If ssh_agent is set to true, the ssh key file provided is irrelevant as the agent  will not respect it anyways.

**Pull request merged**
